sudo: required
services:
  - docker

before_install:
  - docker build -t milper/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true milper/docker-react npm run test

language: generic 